#' Write the raw input template guide
#'
#' Writes a markdown guide explaining how to fill every CSV generated by
#' [draft_input_templates()]. The guide is designed for beginners who are
#' collecting PMSLT model inputs for the first time.
#'
#' @param spec A `pmslt_spec` object.
#' @param output_dir Directory where `README_inputs_raw.md` should be written.
#' @param templates Optional named list of templates. If omitted, templates are
#'   rebuilt from `spec`.
#' @param overwrite Logical. Should an existing guide be overwritten?
#'
#' @return Invisibly returns the guide path.
#' @export
write_input_template_guide <- function(spec,
                                       output_dir = "pmslt_inputs_raw",
                                       templates = NULL,
                                       overwrite = FALSE) {
  validate_spec(spec)

  if (is.null(templates)) {
    templates <- build_input_templates(spec)
  }

  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }

  path <- file.path(output_dir, "README_inputs_raw.md")
  if (file.exists(path) && !isTRUE(overwrite)) {
    stop(
      "File already exists: ", path,
      ". Use `overwrite = TRUE` to replace it.",
      call. = FALSE
    )
  }

  writeLines(input_template_guide_markdown(spec, templates), path)
  invisible(path)
}

input_template_guide_markdown <- function(spec, templates) {
  sections <- c(
    "# PMSLT Raw Input Template Guide",
    "",
    "This folder contains the raw data collection templates for your PMSLT model.",
    "Fill the CSV files before DisMod processing. Leave truly unavailable epidemiological values blank; do not type zero unless zero is the scientific assumption.",
    "",
    "## Model Summary",
    "",
    paste0("- Intervention: ", spec$intervention),
    paste0("- Intervention arms: ", paste(spec$intervention_arms, collapse = ", ")),
    paste0("- Mechanism: ", spec$mechanism),
    paste0("- Diseases: ", paste(spec$diseases, collapse = ", ")),
    paste0("- Risk factors: ", if (length(spec$risk_factors) == 0) "none" else paste(spec$risk_factors, collapse = ", ")),
    paste0(
      "- Risk categories: ",
      if (length(spec$risk_categories) == 0) {
        "none"
      } else {
        paste(
          vapply(
            names(spec$risk_categories),
            function(rf) paste0(rf, " = ", paste(spec$risk_categories[[rf]], collapse = ", ")),
            character(1)
          ),
          collapse = "; "
        )
      }
    ),
    paste0("- Sexes: ", paste(spec$sexes, collapse = ", ")),
    paste0("- Strata: ", paste(spec$strata, collapse = ", ")),
    paste0("- Simulation horizon: ", spec$horizon, " annual cycles"),
    "",
    "## General Rules",
    "",
    "- Keep generated identifier columns unchanged unless the model specification is wrong.",
    "- Rates must be per person-year. For example, 250 per 100,000 person-years should be entered as 0.0025.",
    "- Proportions must be between 0 and 1. For example, 12 percent should be entered as 0.12.",
    "- Use blank cells for unknown values that DisMod should estimate.",
    "- Use zero only when the value is truly zero, such as remission for a non-remitting chronic disease.",
    "- Fill `source` or `data_source` wherever possible. Use enough detail to trace the estimate later.",
    "- Keep sex, age, stratum, disease, and risk-factor labels consistent across files.",
    "",
    unlist(lapply(names(templates), function(name) file_section(name, templates[[name]]))),
    use_after_completion_section()
  )

  paste(sections, collapse = "\n")
}

file_section <- function(template_name, template) {
  info <- template_file_dictionary()[[template_name]]
  if (is.null(info)) {
    info <- list(
      purpose = "Template generated by the package.",
      rows = "One row per generated model unit.",
      columns = list(),
      checks = "Check generated columns against the model specification."
    )
  }

  columns <- names(template)
  column_lines <- unlist(lapply(columns, function(column) {
    explanation <- info$columns[[column]]
    if (is.null(explanation)) {
      explanation <- "Generated package column. Keep unchanged unless you know this field is wrong."
    }
    requirement <- column_requirement(template_name, column)
    marker <- if (requirement %in% c("required", "conditional")) " *" else ""
    c(
      paste0("### `", column, "`", marker),
      "",
      paste0("Requirement: ", requirement, "."),
      "",
      explanation,
      ""
    )
  }))

  c(
    "",
    paste0("## `", template_name, ".csv`"),
    "",
    info$purpose,
    "",
    paste0("Rows: ", info$rows),
    "",
    "Columns:",
    "",
    column_lines,
    "Common checks:",
    "",
    paste0("- ", paste(info$checks, collapse = "\n- ")),
    ""
  )
}

template_file_dictionary <- function() {
  id_age <- "Generated age-band start. Do not edit in the CSV. If the age bands are wrong, regenerate the templates using `age_bands()`."
  id_age_end <- "Generated age-band end. `Inf` means the final open-ended age band, such as 100+. Do not edit manually."
  id_age_label <- "Human-readable age-band label. Keep as generated so files can be checked and joined safely."
  id_sex <- "Generated sex group from `pmslt_spec(sexes = ...)`. Use the same labels in all files."
  id_stratum <- "Generated population stratum from `pmslt_spec(strata = ...)`. For an unstratified model this is usually `total`."
  id_disease <- "Generated disease name from `pmslt_spec(diseases = ...)`. Keep spelling identical across files."
  id_source <- "Enter the data source, such as census year, GBD release, registry name, study citation, table number, or URL."
  id_notes <- "Optional free-text notes. Use this for assumptions, conversions, caveats, or reasons a value is blank."

  list(
    "00_column_dictionary" = list(
      purpose = "Lists every generated template column and whether the user must fill it.",
      rows = "One row per file and column.",
      columns = list(
        file = "Generated template filename.",
        column = "Column name in that template.",
        requirement = "Whether the column is generated, required, conditional, or optional.",
        description = "Plain-language guidance on how to fill or interpret the column."
      ),
      checks = c(
        "Use this file as the quick reference for which fields must be filled.",
        "Required and conditional fields are also marked with `*` in `README_inputs_raw.md`."
      )
    ),
    "00_model_specification" = list(
      purpose = "Records the model design used to generate the templates. This is mainly for checking and documentation.",
      rows = "One row per model specification field.",
      columns = list(
        field = "Generated specification field name. Do not edit unless correcting the model design.",
        value = "Generated value used by the package. Review this file first; if these values are wrong, regenerate the templates rather than editing all CSVs manually.",
        notes = "Explanation of what each model specification field means."
      ),
      checks = c(
        "Confirm the diseases, risk factors, age range, sex groups, strata, and horizon are correct.",
        "If anything is wrong, edit the R call to `pmslt_spec()` and regenerate the templates."
      )
    ),
    "01_population" = list(
      purpose = "Collects base-year population counts. These initialize the main lifetable cohorts.",
      rows = "One row per age, sex, and stratum combination.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        initial_population = "Required. Enter the number of people alive in the base year for this age, sex, and stratum. Use counts, not rates or proportions. Decimals are acceptable only if the source gives modelled population estimates.",
        source = id_source,
        notes = id_notes
      ),
      checks = c(
        "`initial_population` should be non-negative in every row.",
        "Population totals should match your census or official population source after summing rows.",
        "Do not enter population percentages here."
      )
    ),
    "02_all_cause_mortality" = list(
      purpose = "Collects business-as-usual all-cause mortality rates for the main lifetable.",
      rows = "One row per age, sex, and stratum combination.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        acmr_BAU = "Required. Enter the all-cause mortality rate under business-as-usual. Unit: deaths per person-year. Example: 800 deaths per 100,000 person-years becomes 0.008. This is not disease-specific mortality.",
        source = id_source,
        notes = "Use this to record whether the rate came from observed deaths, life tables, GBD, or a forecast. Also record any conversion from deaths per 100,000."
      ),
      checks = c(
        "`acmr_BAU` should be non-negative.",
        "Older age groups should usually have higher mortality than younger age groups.",
        "Do not paste cause-specific mortality into this file."
      )
    ),
    "03_all_cause_morbidity" = list(
      purpose = "Collects all-cause background morbidity for HALY calculations.",
      rows = "One row per age, sex, and stratum combination.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        pYLD_BAU = "Required for HALYs. Enter prevalent years lived with disability per person under business-as-usual. This is often calculated as total prevalent YLD divided by population for the demographic group. It should usually be between 0 and 1.",
        source = id_source,
        notes = "Record whether this came from GBD, national burden of disease estimates, or another source."
      ),
      checks = c(
        "`pYLD_BAU` should usually be between 0 and 1.",
        "This is all-cause morbidity, not disease-specific disability weight.",
        "If only DALYs are being modelled later, still keep the source traceable."
      )
    ),
    "04_life_expectancy" = list(
      purpose = "Collects reference life expectancy used to calculate years of life lost.",
      rows = "One row per age start in the model.",
      columns = list(
        age = "Generated age value. It should match the start of each model age band.",
        expected_years_remaining = "Required for DALY/YLL calculations. Enter remaining life expectancy at this age from the chosen reference life table.",
        source = id_source,
        notes = "Record the life table used, country or standard population, year, and whether values are sex-specific or common across sexes."
      ),
      checks = c(
        "`expected_years_remaining` should be non-negative.",
        "Values should generally decline as age increases.",
        "Use the same reference life table consistently across the project."
      )
    ),
    "05_disease_epidemiology_raw" = list(
      purpose = "Collects raw disease-specific epidemiological parameters before DisMod. This file tells the package what is known and what DisMod may need to estimate.",
      rows = "One row per age, sex, stratum, and disease combination.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        disease = id_disease,
        incidence_rate = "Enter disease incidence rate per person-year if available. Example: 150 per 100,000 person-years becomes 0.0015. Leave blank if unavailable and intended for DisMod.",
        prevalence = "Enter disease prevalence as a proportion between 0 and 1 if available. Example: 8 percent becomes 0.08. This is the proportion with disease at baseline.",
        remission_rate = "Enter remission rate per person-year if relevant. For many chronic non-remitting diseases, enter 0 if that is the explicit modelling assumption. Leave blank only if remission is unknown and should be estimated or reviewed.",
        excess_mortality_rate = "Enter excess mortality among people with the disease, per person-year, if available. This is not the all-cause mortality rate.",
        case_fatality_rate = "Enter the case fatality rate per person-year if this is the parameter used by your disease model. Do not duplicate excess mortality unless that equivalence is a deliberate assumption.",
        disability_weight = "Enter disease-specific disability weight between 0 and 1. Example: 0 means no disability and 1 means equivalent to death. This is not all-cause pYLD.",
        source = id_source,
        notes = "Record assumptions, especially when remission is set to 0 or when incidence/prevalence values were converted from published units."
      ),
      checks = c(
        "For DisMod, aim to provide at least three of incidence, prevalence, remission, excess mortality, and case fatality.",
        "Use blank for unknown values, not zero.",
        "Prevalence and disability weight should be between 0 and 1."
      )
    ),
    "06_dismod_input_skeleton" = list(
      purpose = "Provides a long-format DisMod input skeleton. This can be filled directly or populated from `05_disease_epidemiology_raw.csv`.",
      rows = "One row per age, sex, stratum, disease, and DisMod parameter.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        disease = id_disease,
        parameter = "Generated DisMod parameter name. Allowed values include incidence, prevalence, remission, excess_mortality, and case_fatality.",
        mean_value = "Enter the best estimate for this parameter. Use per person-year for rates and 0 to 1 for proportions.",
        lower_95 = "Optional. Enter lower 95 percent uncertainty bound on the same scale as `mean_value`.",
        upper_95 = "Optional. Enter upper 95 percent uncertainty bound on the same scale as `mean_value`.",
        sample_size = "Optional. Enter sample size or effective sample size if the source provides it. Leave blank if unknown.",
        data_source = id_source,
        quality_flag = "Optional. Use simple values such as High, Medium, or Low to record confidence in the estimate.",
        notes = id_notes
      ),
      checks = c(
        "`lower_95` should be less than or equal to `mean_value`; `upper_95` should be greater than or equal to `mean_value`.",
        "Prevalence rows are proportions, while incidence/remission/mortality rows are rates.",
        "DisMod usually needs at least three epidemiological parameter types per disease."
      )
    ),
    "07_bau_trends" = list(
      purpose = "Collects annual business-as-usual trend assumptions for disease rates.",
      rows = "One row per disease.",
      columns = list(
        disease = id_disease,
        incidence_apc = "Enter annual proportional change in incidence. Example: -0.02 means incidence declines by 2 percent per year. Enter 0 if assuming no BAU trend.",
        cfr_apc = "Enter annual proportional change in case fatality or excess mortality, depending on the disease model. Example: -0.015 means a 1.5 percent annual decline.",
        prevalence_apc = "Optional. Enter annual proportional change in prevalence if you are explicitly modelling prevalence trends outside the disease lifetable. Often this can be left blank.",
        source = id_source,
        notes = "Record how the annual percentage change was estimated, such as Poisson regression, log-linear trend, GBD forecast, or expert assumption."
      ),
      checks = c(
        "Use proportions, not percentages: -2 percent is -0.02.",
        "Enter 0 for deliberately flat trends.",
        "Do not leave trend cells blank if the intended assumption is no change."
      )
    ),
    "08_risk_factor_prevalence" = list(
      purpose = "Collects business-as-usual and intervention risk-factor distributions used to calculate PIFs.",
      rows = "One row per age, sex, stratum, time step, and risk factor. Add or duplicate rows for each risk category as needed.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        time_step = "Generated simulation cycle, where 0 is the base year. Keep this as an integer annual time step.",
        intervention = "Generated intervention arm from `pmslt_spec(intervention_arms = ...)`. Fill `prevalence_intervention` for this specific scenario.",
        risk_factor = "Generated risk factor name. For example: Smoking, BMI, sodium intake.",
        risk_category = "Generated exposure category from `pmslt_spec(risk_categories = ...)`. Examples for smoking: Never, Current, Former_1_5_years, Former_5_plus_years. Regenerate the templates if categories are wrong.",
        prevalence_BAU = "Required for each category. Enter the BAU prevalence proportion for this age, sex, stratum, time step, and category.",
        prevalence_intervention = "Required for PIF-based intervention modelling. Enter the counterfactual intervention prevalence proportion for the same category. If the intervention has no effect in a row, copy `prevalence_BAU`. The PIF cannot be calculated without this intervention distribution.",
        source = id_source,
        notes = "Record intervention assumptions, time-lag assumptions, or how prevalence was projected over time."
      ),
      checks = c(
        "Within each age, sex, stratum, time step, and risk factor, category prevalences should sum to 1 for BAU and intervention.",
        "Risk category labels must exactly match the labels used in `09_relative_risks.csv`.",
        "Use proportions, not percentages."
      )
    ),
    "09_relative_risks" = list(
      purpose = "Collects relative risks connecting risk-factor categories to disease incidence.",
      rows = "One row per age, sex, stratum, risk factor, disease, and risk category.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        risk_factor = "Generated risk factor name. Must match `08_risk_factor_prevalence.csv`.",
        disease = id_disease,
        risk_category = "Generated exposure category from `pmslt_spec(risk_categories = ...)`. Must exactly match `08_risk_factor_prevalence.csv` because both files are generated from the same specification.",
        rr = "Required. Enter the relative risk for this category and disease. The reference category should be 1. Values above 1 increase disease incidence; values below 1 are protective.",
        rr_lower = "Optional. Lower uncertainty bound for the relative risk.",
        rr_upper = "Optional. Upper uncertainty bound for the relative risk.",
        reference_category = "Enter the reference category label, such as Never or Normal weight. This helps reviewers see which group has RR = 1.",
        source = id_source,
        notes = "Record citation, adjustment set, whether RR came from HR/OR conversion, and any age or sex assumptions."
      ),
      checks = c(
        "Every risk category in `08_risk_factor_prevalence.csv` should have a matching RR row for each affected disease.",
        "Reference category RR should be 1.",
        "Do not enter odds ratios as RRs unless the conversion or rare-disease assumption is justified in `notes`."
      )
    ),
    "10_direct_intervention_effects" = list(
      purpose = "Collects direct intervention effects for models where the intervention acts on disease incidence, case fatality, morbidity, or coverage directly.",
      rows = "One row per age, sex, stratum, and disease combination.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        disease = id_disease,
        intervention = "Generated intervention arm from `pmslt_spec(intervention_arms = ...)`. Direct disease effects are scenario-specific.",
        incidence_rr = "Enter direct relative risk multiplier for incidence. Use 1 for no effect. Example: 0.9 means a 10 percent incidence reduction.",
        cfr_rr = "Enter direct relative risk multiplier for case fatality. Use 1 for no effect.",
        morbidity_rr = "Enter direct multiplier for disease morbidity or disability weight. Use 1 for no effect.",
        coverage = "Enter intervention coverage as a proportion between 0 and 1.",
        source = id_source,
        notes = id_notes
      ),
      checks = c(
        "Use 1, not blank, when there is deliberately no effect on a rate.",
        "Coverage should be between 0 and 1.",
        "Do not mix direct effects with PIF effects unless the model specification says `mechanism = \"both\"`."
      )
    ),
    "11_stratum_rate_ratios" = list(
      purpose = "Collects rate ratios needed to disaggregate aggregate rates across equity or population strata.",
      rows = "One row per stratum.",
      columns = list(
        stratum = id_stratum,
        acmr_rate_ratio = "Enter all-cause mortality rate ratio for this stratum compared with the reference stratum.",
        morbidity_rate_ratio = "Enter all-cause morbidity or pYLD rate ratio for this stratum compared with the reference stratum.",
        reference_stratum = "Enter the stratum used as the reference, such as Least_deprived or Q5. The reference stratum usually has rate ratio 1.",
        source = id_source,
        notes = "Record whether ratios are age-standardised, sex-specific, disease-specific, or borrowed from another population."
      ),
      checks = c(
        "Reference stratum should usually have rate ratio 1.",
        "Rate ratios should be positive.",
        "Be explicit about whether the direction is deprived versus least deprived or the reverse."
      )
    ),
    "12_costs" = list(
      purpose = "Collects cost inputs for cost-effectiveness analysis.",
      rows = "One row per age, sex, stratum, and disease combination.",
      columns = list(
        age_start = id_age,
        age_end = id_age_end,
        age_label = id_age_label,
        sex = id_sex,
        stratum = id_stratum,
        disease = id_disease,
        disease_cost = "Enter annual cost per prevalent disease case, in the selected currency and price year.",
        background_cost = "Enter annual non-disease-specific health-system cost per person, if used. Leave blank if background costs are handled elsewhere.",
        currency = "Enter currency code, such as AUD, NZD, USD, or GBP.",
        price_year = "Enter the price year for costs, such as 2024.",
        source = id_source,
        notes = "Record whether costs are health-system, societal, patient, intervention, or disease-management costs."
      ),
      checks = c(
        "Costs should be non-negative.",
        "Keep currency and price year consistent.",
        "Do not mix one-off intervention costs with annual disease-management costs without noting the difference."
      )
    )
  )
}

use_after_completion_section <- function() {
  c(
    "",
    "## After Completing These Files",
    "",
    "1. Check that all required population, all-cause mortality, all-cause morbidity, and life expectancy fields are filled.",
    "2. Run `diagnose_missing_parameters()` on the disease epidemiology file to see whether each disease is ready for DisMod.",
    "3. Convert or copy disease rows into the DisMod workflow using `06_dismod_input_skeleton.csv`.",
    "4. After DisMod returns coherent estimates, use the DisMod outputs rather than the raw disease epidemiology file for PMSLT simulation inputs.",
    "5. Keep these raw files unchanged as an audit trail. If assumptions change, create a new input folder rather than overwriting the original evidence collection."
  )
}

column_dictionary_template <- function(templates) {
  rows <- lapply(names(templates), function(template_name) {
    info <- template_file_dictionary()[[template_name]]
    data.frame(
      file = paste0(template_name, ".csv"),
      column = names(templates[[template_name]]),
      requirement = vapply(
        names(templates[[template_name]]),
        function(column) column_requirement(template_name, column),
        character(1)
      ),
      description = vapply(
        names(templates[[template_name]]),
        function(column) {
          if (!is.null(info$columns[[column]])) {
            info$columns[[column]]
          } else {
            "Generated package column. Keep unchanged unless you know this field is wrong."
          }
        },
        character(1)
      ),
      stringsAsFactors = FALSE
    )
  })

  do.call(rbind, rows)
}

column_requirement <- function(template_name, column) {
  req <- column_requirement_dictionary()[[template_name]]
  if (is.null(req)) {
    return("generated")
  }

  for (requirement in names(req)) {
    if (column %in% req[[requirement]]) {
      return(requirement)
    }
  }

  "generated"
}

column_requirement_dictionary <- function() {
  common_generated <- c(
    "age_start", "age_end", "age_label", "sex", "stratum", "disease",
    "time_step", "intervention", "risk_factor", "risk_category", "parameter",
    "age", "field", "value"
  )

  list(
    "00_column_dictionary" = list(
      generated = c("file", "column", "requirement", "description")
    ),
    "00_model_specification" = list(
      generated = c("field", "value", "notes")
    ),
    "01_population" = list(
      generated = common_generated,
      required = c("initial_population", "source"),
      optional = "notes"
    ),
    "02_all_cause_mortality" = list(
      generated = common_generated,
      required = c("acmr_BAU", "source"),
      optional = "notes"
    ),
    "03_all_cause_morbidity" = list(
      generated = common_generated,
      required = c("pYLD_BAU", "source"),
      optional = "notes"
    ),
    "04_life_expectancy" = list(
      generated = common_generated,
      required = c("expected_years_remaining", "source"),
      optional = "notes"
    ),
    "05_disease_epidemiology_raw" = list(
      generated = common_generated,
      conditional = c(
        "incidence_rate", "prevalence", "remission_rate",
        "excess_mortality_rate", "case_fatality_rate"
      ),
      required = c("disability_weight", "source"),
      optional = "notes"
    ),
    "06_dismod_input_skeleton" = list(
      generated = common_generated,
      conditional = c(
        "mean_value", "lower_95", "upper_95", "sample_size",
        "data_source", "quality_flag"
      ),
      optional = "notes"
    ),
    "07_bau_trends" = list(
      generated = common_generated,
      required = c("incidence_apc", "cfr_apc", "source"),
      optional = c("prevalence_apc", "notes")
    ),
    "08_risk_factor_prevalence" = list(
      generated = common_generated,
      required = c("prevalence_BAU", "prevalence_intervention", "source"),
      optional = "notes"
    ),
    "09_relative_risks" = list(
      generated = common_generated,
      required = c("rr", "reference_category", "source"),
      optional = c("rr_lower", "rr_upper", "notes")
    ),
    "10_direct_intervention_effects" = list(
      generated = common_generated,
      required = c("incidence_rr", "cfr_rr", "morbidity_rr", "coverage", "source"),
      optional = "notes"
    ),
    "11_stratum_rate_ratios" = list(
      generated = common_generated,
      required = c("acmr_rate_ratio", "morbidity_rate_ratio", "reference_stratum", "source"),
      optional = "notes"
    ),
    "12_costs" = list(
      generated = common_generated,
      required = c("disease_cost", "currency", "price_year", "source"),
      optional = c("background_cost", "notes")
    )
  )
}
