#' Validate raw PMSLT input templates
#'
#' Checks raw CSV files generated by [draft_input_templates()] before DisMod
#' processing. The validation is schema-driven and returns all issues it can
#' find instead of stopping at the first problem.
#'
#' @param input_dir Directory containing raw input CSV files.
#' @param spec Optional `pmslt_spec` object used to determine which optional
#'   template files and generated values are expected. If omitted, the function
#'   uses `00_model_specification.csv` when possible.
#'
#' @return A data frame with class `pmslt_validation_issues` and columns
#'   `file`, `row`, `column`, `severity`, `message`, and `suggested_fix`. If
#'   `input_dir` does not exist or is not a directory, the function returns an
#'   error-severity issue table instead of throwing a low-level file error.
#' @export
#'
#' @examples
#' \dontrun{
#' spec <- pmslt_spec(
#'   intervention = "Tobacco tax",
#'   mechanism = "direct",
#'   diseases = "CHD"
#' )
#' draft_input_templates(spec, output_dir = tempdir(), overwrite = TRUE)
#' issues <- validate_raw_inputs(tempdir(), spec)
#' issues <- validate_raw_inputs(tempdir())
#' }
validate_raw_inputs <- function(input_dir, spec = NULL) {
  if (!is.character(input_dir) || length(input_dir) != 1 || is.na(input_dir)) {
    return(append_validation_issue(
      empty_validation_issues(),
      file = NA_character_,
      row = NA_integer_,
      column = NA_character_,
      severity = "error",
      message = "`input_dir` must be a single folder path.",
      suggested_fix = "Pass the folder that contains the raw CSV templates generated by draft_input_templates()."
    ))
  }
  if (file.exists(input_dir) && !dir.exists(input_dir)) {
    return(append_validation_issue(
      empty_validation_issues(),
      file = NA_character_,
      row = NA_integer_,
      column = NA_character_,
      severity = "error",
      message = paste0("Raw input path is not a folder: ", input_dir, "."),
      suggested_fix = "Pass the folder that contains the raw CSV templates, not a single CSV file."
    ))
  }
  if (!dir.exists(input_dir)) {
    return(append_validation_issue(
      empty_validation_issues(),
      file = NA_character_,
      row = NA_integer_,
      column = NA_character_,
      severity = "error",
      message = paste0("Raw input folder does not exist: ", input_dir, "."),
      suggested_fix = "Create the folder or check the spelling of input_dir, then run draft_input_templates() if templates have not been generated yet."
    ))
  }
  if (!is.null(spec)) {
    validate_spec(spec)
  }

  schemas <- pmslt_input_schemas()
  expected_names <- expected_raw_template_names(input_dir, spec, schemas)
  expected_files <- paste0(expected_names, ".csv")
  issues <- empty_validation_issues()

  csv_files <- sort(list.files(input_dir, pattern = "\\.csv$", ignore.case = TRUE))

  for (file in expected_files) {
    path <- file.path(input_dir, file)
    if (!file.exists(path)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = NA_integer_,
        column = NA_character_,
        severity = "error",
        message = paste0("Required raw input file '", file, "' is missing."),
        suggested_fix = paste0("Regenerate the templates or add '", file, "' to the raw input folder.")
      )
    }
  }

  issues <- append_duplicate_file_issues(issues, csv_files, expected_files)

  for (template_name in expected_names) {
    file <- paste0(template_name, ".csv")
    path <- file.path(input_dir, file)
    if (!file.exists(path)) {
      next
    }
    schema <- schemas[[template_name]]
    file_issues <- validate_one_raw_file(path, file, schema, spec)
    issues <- append_validation_issues(issues, file_issues)
  }

  finalize_validation_issues(issues)
}

empty_validation_issues <- function() {
  finalize_validation_issues(data.frame(
    file = character(),
    row = integer(),
    column = character(),
    severity = character(),
    message = character(),
    suggested_fix = character(),
    stringsAsFactors = FALSE
  ))
}

new_validation_issue <- function(file,
                                 row,
                                 column,
                                 severity,
                                 message,
                                 suggested_fix) {
  finalize_validation_issues(data.frame(
    file = as.character(file),
    row = as.integer(row),
    column = as.character(column),
    severity = as.character(severity),
    message = as.character(message),
    suggested_fix = as.character(suggested_fix),
    stringsAsFactors = FALSE
  ))
}

append_validation_issue <- function(issues,
                                    file,
                                    row,
                                    column,
                                    severity,
                                    message,
                                    suggested_fix) {
  append_validation_issues(
    issues,
    new_validation_issue(file, row, column, severity, message, suggested_fix)
  )
}

append_validation_issues <- function(issues, new_issues) {
  if (nrow(new_issues) == 0) {
    return(finalize_validation_issues(issues))
  }
  old <- as.data.frame(issues, stringsAsFactors = FALSE)
  new <- as.data.frame(new_issues, stringsAsFactors = FALSE)
  class(old) <- "data.frame"
  class(new) <- "data.frame"
  finalize_validation_issues(rbind(old, new))
}

finalize_validation_issues <- function(issues) {
  issues <- as.data.frame(issues, stringsAsFactors = FALSE)
  expected <- validation_issue_columns()
  issues <- issues[, expected, drop = FALSE]
  issues$row <- as.integer(issues$row)
  row.names(issues) <- NULL
  class(issues) <- c("pmslt_validation_issues", "data.frame")
  issues
}

validation_issue_columns <- function() {
  c("file", "row", "column", "severity", "message", "suggested_fix")
}

#' @export
print.pmslt_validation_issues <- function(x, ...) {
  n <- nrow(x)
  cat("PMSLT raw input validation issues\n")
  cat("Issues: ", n, "\n", sep = "")
  if (n > 0) {
    counts <- table(x$severity)
    summary <- paste(paste(names(counts), as.integer(counts), sep = ": "), collapse = ", ")
    cat("By severity: ", summary, "\n", sep = "")
    print.data.frame(utils::head(unclass(x), 10), row.names = FALSE)
    if (n > 10) {
      cat("... ", n - 10, " more issue(s)\n", sep = "")
    }
  }
  invisible(x)
}

#' Summarise raw input validation issues
#'
#' Converts the issue table returned by [validate_raw_inputs()] into a compact
#' beginner-facing summary. This helper does not re-run validation and does not
#' modify any files.
#'
#' @param issues A validation issue data frame returned by
#'   [validate_raw_inputs()]. It must contain `file`, `row`, `column`,
#'   `severity`, `message`, and `suggested_fix`.
#'
#' @return A list with class `summarised_raw_input_issues` containing
#'   `can_proceed`, `issue_count`, `error_count`, `warning_count`,
#'   `files_with_issues`, `summary_by_file`, and `next_step`.
#' @export
#'
#' @examples
#' \dontrun{
#' issues <- validate_raw_inputs("inputs_raw", spec)
#' summarise_raw_input_issues(issues)
#' }
summarise_raw_input_issues <- function(issues) {
  validate_issue_table_format(issues)
  issues <- as.data.frame(issues, stringsAsFactors = FALSE)

  issue_count <- nrow(issues)
  severity <- normalise_issue_severity(issues$severity)
  error_count <- sum(severity == "error", na.rm = TRUE)
  warning_count <- sum(severity == "warning", na.rm = TRUE)
  can_proceed <- error_count == 0

  summary_by_file <- summarise_issues_by_file(issues, severity)
  files_with_issues <- summary_by_file$file

  next_step <- raw_issue_next_step(issue_count, error_count, warning_count)

  out <- list(
    can_proceed = can_proceed,
    issue_count = issue_count,
    error_count = error_count,
    warning_count = warning_count,
    files_with_issues = files_with_issues,
    summary_by_file = summary_by_file,
    next_step = next_step
  )
  class(out) <- "summarised_raw_input_issues"
  out
}

validate_issue_table_format <- function(issues) {
  if (!is.data.frame(issues)) {
    stop(
      "`issues` must be the issue table returned by validate_raw_inputs().",
      call. = FALSE
    )
  }

  missing_columns <- setdiff(validation_issue_columns(), names(issues))
  if (length(missing_columns) > 0) {
    stop(
      "`issues` is missing required column(s): ",
      paste(missing_columns, collapse = ", "),
      ". Use the data frame returned by validate_raw_inputs().",
      call. = FALSE
    )
  }

  invisible(TRUE)
}

normalise_issue_severity <- function(severity) {
  tolower(trimws(as.character(severity)))
}

summarise_issues_by_file <- function(issues, severity) {
  if (nrow(issues) == 0) {
    return(data.frame(
      file = character(),
      issue_count = integer(),
      error_count = integer(),
      warning_count = integer(),
      stringsAsFactors = FALSE
    ))
  }

  file <- as.character(issues$file)
  file[is.na(file) | !nzchar(trimws(file))] <- "(input folder)"
  files <- sort(unique(file))

  rows <- lapply(files, function(this_file) {
    in_file <- file == this_file
    data.frame(
      file = this_file,
      issue_count = sum(in_file),
      error_count = sum(in_file & severity == "error", na.rm = TRUE),
      warning_count = sum(in_file & severity == "warning", na.rm = TRUE),
      stringsAsFactors = FALSE
    )
  })

  out <- do.call(rbind, rows)
  row.names(out) <- NULL
  out
}

raw_issue_next_step <- function(issue_count, error_count, warning_count) {
  if (issue_count == 0) {
    return("No raw input issues were found. You can proceed to the next workflow step.")
  }
  if (error_count > 0) {
    return("Fix the error issues before proceeding to disease consistency solving or PMSLT-ready input preparation.")
  }
  if (warning_count > 0) {
    return("You can proceed, but review the warnings first to make sure the raw inputs are intentional.")
  }
  "Review the validation issues before proceeding."
}

#' @export
print.summarised_raw_input_issues <- function(x, ...) {
  cat("Raw input validation summary\n")
  cat("Can proceed: ", if (isTRUE(x$can_proceed)) "yes" else "no", "\n", sep = "")
  cat("Issues: ", x$issue_count, " (errors: ", x$error_count, ", warnings: ", x$warning_count, ")\n", sep = "")
  cat("Next step: ", x$next_step, "\n", sep = "")

  if (nrow(x$summary_by_file) > 0) {
    cat("\nFiles with issues:\n")
    print.data.frame(x$summary_by_file, row.names = FALSE)
  }

  invisible(x)
}

#' Check whether raw input templates are ready for the next workflow step
#'
#' Runs [validate_raw_inputs()] and [summarise_raw_input_issues()] in one
#' beginner-facing step. This helper does not add validation rules and does not
#' modify any files.
#'
#' @param input_dir Directory containing raw input CSV files.
#' @param spec Optional `pmslt_spec` object passed to [validate_raw_inputs()].
#'
#' @return A list with class `raw_input_readiness_check` containing `issues`,
#'   `summary`, `can_proceed`, and `next_step`.
#' @export
#'
#' @examples
#' \dontrun{
#' readiness <- check_raw_input_readiness("inputs_raw", spec)
#' readiness$can_proceed
#' readiness$issues
#' }
check_raw_input_readiness <- function(input_dir, spec = NULL) {
  issues <- validate_raw_inputs(input_dir, spec = spec)
  summary <- summarise_raw_input_issues(issues)

  out <- list(
    issues = issues,
    summary = summary,
    can_proceed = summary$can_proceed,
    next_step = summary$next_step
  )
  class(out) <- "raw_input_readiness_check"
  out
}

#' @export
print.raw_input_readiness_check <- function(x, ...) {
  cat("Raw input readiness check\n")
  cat("Can proceed: ", if (isTRUE(x$can_proceed)) "yes" else "no", "\n", sep = "")
  cat(
    "Issues found: ",
    x$summary$issue_count,
    " (errors: ",
    x$summary$error_count,
    ", warnings: ",
    x$summary$warning_count,
    ")\n",
    sep = ""
  )
  cat("Next step: ", x$next_step, "\n", sep = "")

  if (!isTRUE(x$can_proceed)) {
    cat("Inspect the $issues table to see what to fix.\n")
  } else if (x$summary$warning_count > 0) {
    cat("Review the warnings in $issues before moving on.\n")
  }

  invisible(x)
}

expected_raw_template_names <- function(input_dir, spec, schemas) {
  if (!is.null(spec)) {
    return(names(build_input_templates(spec)))
  }

  model_spec_path <- file.path(input_dir, "00_model_specification.csv")
  if (file.exists(model_spec_path)) {
    inferred <- tryCatch(
      infer_template_names_from_model_spec(model_spec_path),
      error = function(e) NULL
    )
    if (!is.null(inferred)) {
      return(intersect(inferred, names(schemas)))
    }
  }

  names(schemas)
}

infer_template_names_from_model_spec <- function(path) {
  data <- utils::read.csv(
    path,
    stringsAsFactors = FALSE,
    na.strings = c("", "NA"),
    check.names = FALSE
  )
  if (!all(c("field", "value") %in% names(data))) {
    return(NULL)
  }

  lookup <- stats::setNames(as.character(data$value), as.character(data$field))
  mechanism <- lookup[["mechanism"]]
  strata <- split_semicolon_values(lookup[["strata"]])
  cost_effectiveness <- isTRUE(toupper(lookup[["cost_effectiveness"]]) == "TRUE")

  names <- c(
    "00_column_dictionary",
    "00_model_specification",
    "01_population",
    "02_all_cause_mortality",
    "03_all_cause_morbidity",
    "04_life_expectancy",
    "05_disease_epidemiology_raw",
    "06_dismod_input_skeleton",
    "07_bau_trends"
  )
  if (mechanism %in% c("risk_factor", "both")) {
    names <- c(names, "08_risk_factor_prevalence", "09_relative_risks")
  }
  if (mechanism %in% c("direct", "both")) {
    names <- c(names, "10_direct_intervention_effects")
  }
  if (length(strata) > 1 || !identical(tolower(strata), "total")) {
    names <- c(names, "11_stratum_rate_ratios")
  }
  if (cost_effectiveness) {
    names <- c(names, "12_costs")
  }
  names
}

split_semicolon_values <- function(x) {
  if (is.null(x) || length(x) == 0 || is.na(x) || !nzchar(x)) {
    return(character())
  }
  trimws(strsplit(x, ";", fixed = TRUE)[[1]])
}

append_duplicate_file_issues <- function(issues, csv_files, expected_files) {
  expected_stems <- sub("\\.csv$", "", expected_files)
  for (stem in expected_stems) {
    pattern <- paste0("^", escape_regex(stem), "([ _-]*copy| \\([0-9]+\\)|_[0-9]+|-copy)?\\.csv$")
    matches <- csv_files[grepl(pattern, csv_files, ignore.case = TRUE)]
    duplicates <- setdiff(matches, paste0(stem, ".csv"))
    for (duplicate in sort(duplicates)) {
      issues <- append_validation_issue(
        issues,
        file = duplicate,
        row = NA_integer_,
        column = NA_character_,
        severity = "error",
        message = paste0("Unexpected duplicate raw input file '", duplicate, "' was found."),
        suggested_fix = paste0("Keep one file named '", stem, ".csv' and move or delete the duplicate copy.")
      )
    }
  }
  issues
}

escape_regex <- function(x) {
  gsub("([][{}()+*^$|\\\\?.])", "\\\\\\1", x)
}

validate_one_raw_file <- function(path, file, schema, spec) {
  issues <- empty_validation_issues()
  data <- tryCatch(
    utils::read.csv(
      path,
      stringsAsFactors = FALSE,
      na.strings = c("", "NA"),
      check.names = FALSE,
      colClasses = "character"
    ),
    error = function(e) e
  )
  if (inherits(data, "error")) {
    return(append_validation_issue(
      issues,
      file = file,
      row = NA_integer_,
      column = NA_character_,
      severity = "error",
      message = paste0("File '", file, "' could not be read as a CSV."),
      suggested_fix = "Open the file, check that it is a valid comma-separated CSV, then save it again."
    ))
  }

  duplicated_columns <- unique(names(data)[duplicated(names(data))])
  for (column in duplicated_columns) {
    issues <- append_validation_issue(
      issues,
      file = file,
      row = NA_integer_,
      column = column,
      severity = "error",
      message = paste0("Column '", column, "' appears more than once."),
      suggested_fix = paste0("Keep one column named '", column, "' and remove or rename the duplicate column.")
    )
  }

  expected_columns <- schema$columns$column
  missing_columns <- setdiff(expected_columns, names(data))
  for (column in missing_columns) {
    issues <- append_validation_issue(
      issues,
      file = file,
      row = NA_integer_,
      column = column,
      severity = "error",
      message = paste0("Expected column '", column, "' is missing."),
      suggested_fix = paste0("Add column '", column, "' or regenerate this template file.")
    )
  }

  unexpected_columns <- setdiff(names(data), expected_columns)
  for (column in unexpected_columns) {
    issues <- append_validation_issue(
      issues,
      file = file,
      row = NA_integer_,
      column = column,
      severity = "warning",
      message = paste0("Column '", column, "' is not part of this raw input template."),
      suggested_fix = paste0("Check whether '", column, "' was added by mistake. If it is only a note for your records, keep it outside the template CSV.")
    )
  }

  present_expected <- intersect(expected_columns, names(data))
  issues <- validate_required_missing_values(issues, data, file, schema)
  for (column in present_expected) {
    validation <- raw_column_validation(schema$template_name, column)
    issues <- validate_column_values(issues, data, file, column, validation, spec)
  }
  issues <- validate_age_consistency(issues, data, file)
  issues <- validate_uncertainty_consistency(issues, data, file)
  issues <- validate_duplicate_key_rows(issues, data, file, schema)
  issues <- validate_stratum_rate_ratio_completeness(issues, data, file, schema, spec)

  issues
}

validate_required_missing_values <- function(issues, data, file, schema) {
  required_columns <- schema$columns$column[schema$columns$requirement == "required"]
  for (column in intersect(required_columns, names(data))) {
    missing <- is.na(data[[column]]) | !nzchar(trimws(data[[column]]))
    if (any(missing)) {
      for (row in which(missing)) {
        issues <- append_validation_issue(
          issues,
          file = file,
          row = row,
          column = column,
          severity = "error",
          message = paste0("Required column '", column, "' is blank."),
          suggested_fix = paste0("Enter a value for '", column, "' in this row.")
        )
      }
    }
  }
  issues
}

raw_column_validation <- function(template_name, column) {
  validation <- column_validation_dictionary()[[template_name]][[column]]
  if (is.null(validation)) {
    validation <- list(type = "none")
  }
  validation
}

validate_column_values <- function(issues, data, file, column, validation, spec) {
  type <- validation$type %||% "none"
  values <- data[[column]]
  present <- !(is.na(values) | !nzchar(trimws(values)))
  if (!any(present)) {
    return(issues)
  }

  if (type %in% numeric_validation_types()) {
    numeric_values <- suppressWarnings(as.numeric(values))
    non_numeric <- present & is.na(numeric_values)
    if (any(non_numeric)) {
      for (row in which(non_numeric)) {
        issues <- append_validation_issue(
          issues,
          file = file,
          row = row,
          column = column,
          severity = "error",
          message = paste0("Column '", column, "' contains a non-numeric entry."),
          suggested_fix = paste0("Ensure all entries in '", column, "' are numeric.")
        )
      }
    }
    checkable <- present & !is.na(numeric_values)
    issues <- validate_numeric_bounds(issues, file, column, type, numeric_values, checkable)
  }

  if (type == "integer") {
    numeric_values <- suppressWarnings(as.numeric(values))
    integer_bad <- present & !is.na(numeric_values) & abs(numeric_values - round(numeric_values)) > .Machine$double.eps^0.5
    for (row in which(integer_bad)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = column,
        severity = "error",
        message = paste0("Column '", column, "' must contain whole numbers."),
        suggested_fix = paste0("Use integer values such as 0, 1, or 2 in '", column, "'.")
      )
    }
  }

  allowed_values <- allowed_values_for_column(column, validation, spec)
  if (length(allowed_values) > 0) {
    invalid <- present & !values %in% allowed_values
    for (row in which(invalid)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = column,
        severity = "error",
        message = paste0("Column '", column, "' contains value '", values[[row]], "', which is not expected."),
        suggested_fix = paste0("Use one of: ", paste(allowed_values, collapse = ", "), ".")
      )
    }
  }

  if (type == "currency_code") {
    invalid_currency <- present & !grepl("^[A-Z]{3}$", as.character(values))
    for (row in which(invalid_currency)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = column,
        severity = "error",
        message = paste0("Column '", column, "' must contain a three-letter currency code."),
        suggested_fix = paste0("Use an uppercase ISO-style currency code such as AUD, NZD, USD, or GBP in '", column, "'.")
      )
    }
  }

  issues
}

numeric_validation_types <- function() {
  c(
    "non_negative_rate",
    "non_negative_number",
    "proportion_0_1",
    "positive_number",
    "annual_proportional_change",
    "integer",
    "calendar_year",
    "dismod_parameter_value"
  )
}

validate_numeric_bounds <- function(issues, file, column, type, values, checkable) {
  if (type %in% c("non_negative_rate", "non_negative_number", "dismod_parameter_value")) {
    bad <- checkable & values < 0
    for (row in which(bad)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = column,
        severity = "error",
        message = paste0("Column '", column, "' contains a negative value."),
        suggested_fix = paste0("Enter a value of 0 or greater in '", column, "'.")
      )
    }
  }

  if (type == "proportion_0_1") {
    bad <- checkable & (values < 0 | values > 1)
    for (row in which(bad)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = column,
        severity = "error",
        message = paste0("Column '", column, "' must be between 0 and 1."),
        suggested_fix = paste0("Enter '", column, "' as a proportion, for example 12 percent should be 0.12.")
      )
    }
  }

  if (type == "positive_number") {
    bad <- checkable & values <= 0
    for (row in which(bad)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = column,
        severity = "error",
        message = paste0("Column '", column, "' must be greater than 0."),
        suggested_fix = paste0("Enter a positive value in '", column, "'.")
      )
    }
  }

  if (type == "calendar_year") {
    bad <- checkable & (values < 1800 | values > 2200 | abs(values - round(values)) > .Machine$double.eps^0.5)
    for (row in which(bad)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = column,
        severity = "error",
        message = paste0("Column '", column, "' must be a calendar year."),
        suggested_fix = paste0("Enter a four-digit year such as 2024 in '", column, "'.")
      )
    }
  }
  issues
}

allowed_values_for_column <- function(column, validation, spec) {
  if (!is.null(validation$allowed_values)) {
    return(as.character(validation$allowed_values))
  }
  if (is.null(spec)) {
    return(character())
  }
  switch(
    column,
    sex = as.character(spec$sexes),
    stratum = as.character(spec$strata),
    disease = as.character(spec$diseases),
    intervention = as.character(spec$intervention_arms),
    risk_factor = as.character(spec$risk_factors),
    risk_category = unique(unlist(spec$risk_categories, use.names = FALSE)),
    age_label = as.character(spec$ages$age_label),
    age_start = as.character(spec$ages$age_start),
    age_end = as.character(spec$ages$age_end),
    age = as.character(spec$ages$age_start),
    time_step = as.character(seq.int(0, spec$horizon)),
    character()
  )
}

validate_age_consistency <- function(issues, data, file) {
  if (!all(c("age_start", "age_end") %in% names(data))) {
    return(issues)
  }
  age_start <- suppressWarnings(as.numeric(data$age_start))
  age_end <- suppressWarnings(as.numeric(data$age_end))
  checkable <- !is.na(age_start) & !is.na(age_end)
  bad <- checkable & age_start > age_end
  for (row in which(bad)) {
    issues <- append_validation_issue(
      issues,
      file = file,
      row = row,
      column = "age_end",
      severity = "error",
      message = "Age band has age_start greater than age_end.",
      suggested_fix = "Check the age_start and age_end values or regenerate the templates from the model specification."
    )
  }
  issues
}

validate_uncertainty_consistency <- function(issues, data, file) {
  if (all(c("lower_95", "mean_value") %in% names(data))) {
    lower <- suppressWarnings(as.numeric(data$lower_95))
    mean <- suppressWarnings(as.numeric(data$mean_value))
    bad <- !is.na(lower) & !is.na(mean) & lower > mean
    for (row in which(bad)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = "lower_95",
        severity = "error",
        message = "Column 'lower_95' is greater than 'mean_value'.",
        suggested_fix = "Enter lower_95 on the same scale as mean_value and make it less than or equal to mean_value."
      )
    }
  }
  if (all(c("upper_95", "mean_value") %in% names(data))) {
    upper <- suppressWarnings(as.numeric(data$upper_95))
    mean <- suppressWarnings(as.numeric(data$mean_value))
    bad <- !is.na(upper) & !is.na(mean) & upper < mean
    for (row in which(bad)) {
      issues <- append_validation_issue(
        issues,
        file = file,
        row = row,
        column = "upper_95",
        severity = "error",
        message = "Column 'upper_95' is less than 'mean_value'.",
        suggested_fix = "Enter upper_95 on the same scale as mean_value and make it greater than or equal to mean_value."
      )
    }
  }
  issues
}

validate_duplicate_key_rows <- function(issues, data, file, schema) {
  key_columns <- schema$key_columns
  if (is.null(key_columns) || length(key_columns) == 0) {
    return(issues)
  }
  if (!all(key_columns %in% names(data))) {
    return(issues)
  }
  if (nrow(data) == 0) {
    return(issues)
  }

  key_data <- data[key_columns]
  key_data[] <- lapply(key_data, function(x) {
    x <- trimws(as.character(x))
    x[is.na(x)] <- ""
    x
  })
  key_values <- do.call(paste, c(key_data, sep = "\r"))
  duplicate_rows <- which(duplicated(key_values))
  for (row in duplicate_rows) {
    issues <- append_validation_issue(
      issues,
      file = file,
      row = row,
      column = paste(key_columns, collapse = ", "),
      severity = "error",
      message = paste0(
        "This row repeats the same identifying values as an earlier row in '",
        file,
        "'."
      ),
      suggested_fix = paste0(
        "Keep one row for each unique combination of ",
        paste(key_columns, collapse = ", "),
        "."
      )
    )
  }
  issues
}

validate_stratum_rate_ratio_completeness <- function(issues, data, file, schema, spec) {
  if (!identical(schema$template_name, "11_stratum_rate_ratios") || is.null(spec)) {
    return(issues)
  }
  needed_columns <- c("age_start", "sex", "stratum", "parameter")
  if (!all(needed_columns %in% names(data))) {
    return(issues)
  }

  expected <- expand.grid(
    age_start = as.character(spec$ages$age_start),
    sex = as.character(spec$sexes),
    stratum = as.character(spec$strata),
    parameter = stratum_rate_ratio_parameter_names(),
    stringsAsFactors = FALSE
  )
  observed <- data[needed_columns]
  observed[] <- lapply(observed, function(x) {
    x <- trimws(as.character(x))
    x[is.na(x)] <- ""
    x
  })
  names(observed) <- needed_columns

  missing <- expected[!equity_key_in(expected, observed, needed_columns), , drop = FALSE]
  for (i in seq_len(nrow(missing))) {
    issues <- append_validation_issue(
      issues,
      file = file,
      row = NA_integer_,
      column = paste(needed_columns, collapse = ", "),
      severity = "error",
      message = paste0(
        "Stratum rate ratios are incomplete for age_start=", missing$age_start[[i]],
        ", sex=", missing$sex[[i]],
        ", stratum=", missing$stratum[[i]],
        ", parameter=", missing$parameter[[i]], "."
      ),
      suggested_fix = "Add one row for every generated age_start, sex, stratum, and parameter combination, or regenerate the raw templates."
    )
  }

  issues
}

`%||%` <- function(x, y) {
  if (is.null(x)) y else x
}
